[package]
name = "neumann"
version = "0.1.0"
authors = ["Raimundo Saona <rasa200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minilp = "0.2.2"
ndarray = "0.13.1"
itertools = "0.9.0"

[dev-dependencies]
test-case = "1.0.0"
approx = "0.3.2"
preexplorer = "0.3.2"
